Desktop/hudl/config/routes.rb
Hudl::Application.routes.draw do
  resources :workouts

end

Desktop/hudl/app/models/workout.rb
class Workout < ActiveRecord::Base
end

Desktop/hudl/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Desktop/hudl/app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.all
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render action: 'show', status: :created, location: @workout }
      else
        format.html { render action: 'new' }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to workouts_url, notice: 'Workout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:name, :bodyPart, :favorite)
    end
end

Desktop/hudl/app/helpers/application_helper.rb
module ApplicationHelper
end

Desktop/hudl/app/helpers/workouts_helper.rb
module WorkoutsHelper
end

Desktop/hudl/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkoutRoutines</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Desktop/hudl/app/views/workouts/_all.html.erb
<h3>List of Workouts</h3>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Body Part Targeted</th>
      <th>Picture</th>
      <th>Favorite</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= workout.name %></td>
        <td><%= workout.bodyPart %></td>
        <td><img src="<%= workout.image %>"</img></td>

        <% if workout.favorite == true %>
        <td><span class="glyphicon glyphicon-star"></span> </td>
        <td><%= link_to 'Remove from Favorites', edit_workout_path(workout) %></td> 
        <% else %>
        <td></td>
        <td><%= link_to 'Add to Favorites', edit_workout_path(workout) %></td>  
        <%end%>

        

      </tr>
    <%end%>
  </tbody>
  </table>

Desktop/hudl/app/views/workouts/_favorite.html.erb
<div class="col-lg-8">
<h3>List of Workouts</h3>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Body Part Targeted</th>
      <th>Picture</th>
      <th>Favorite</th>
      <th>Edit</th>
    </tr>
  </thead>

  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <% if workout.favorite == true %>
        <td><%= workout.name %></td>
        <td><%= workout.bodyPart %></td>
        <td><img src="<%= workout.image %>"</img></td>
        <td><span class="glyphicon glyphicon-star"></span> </td>
        <td><%= link_to 'Remove from Favorites', edit_workout_path(workout) %></td> 
        <%end%>
      </tr>
    <%end%>
  </tbody>
  </table>

Desktop/hudl/app/views/workouts/_form.html.erb
<%= form_for(@workout) do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <b>Name: </b><%= @workout.name %>
  </div>
  <div class="field">
    <b>Favorite? </b><%= f.check_box :favorite %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Desktop/hudl/app/views/workouts/edit.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <p class="navbar-text">Workout</p>
    </div>
  </div>
  </div>

<div class="col-md-6 edit">


  <h5>Click on the checkbox next to Favorite to add it to the list.
  </br>Uncheck the checkbox to remove it from the list.</h5>

<h3>Adding to Favorites</h3>

<%= render 'form' %>

<%= link_to 'Back', workouts_path %>
</div>

Desktop/hudl/app/views/workouts/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <p class="navbar-text">Workout</p>
      <button type="button" class="btn btn-default navbar-btn" onclick="onAllClick()">All Workouts</button>
      <button type="button" class="btn btn-default navbar-btn" onclick="onFavoriteClick()">Favorite</button>
    </div>
  </div>
  </div>

  </br>
    <h4>Read through the list of workouts, and choose the workout that best targets the area you want to improve. </br> In additon, add workouts to your favorites to access them easily.</h4>

<div class="col-md-6" id="all">
  <%= render 'all' %>
</div>

<div class="col-md-6" id="favorite" style="display: none">
  <%= render 'favorite' %>
</div>


<script type="text/javascript">
  function onFavoriteClick() {
    document.getElementById("favorite").style.display = "block";
    document.getElementById("all").style.display = "none";
  }

  function onAllClick() {
    document.getElementById("favorite").style.display = "none";
    document.getElementById("all").style.display = "block";
  }
</script>

Desktop/hudl/app/views/workouts/show.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <p class="navbar-text">Workout</p>
    </div>
  </div>
  </div>

<div class="col-md-6">

<h3>Adding to Favorites</h3>

<p>
  <strong>Name:</strong>
  <%= @workout.name %>
</p>

<p>
  <strong>Body Part:</strong>
  <%= @workout.bodyPart %>
</p>

<p>
  <strong>Image:</strong>
  <img src="<%= @workout.image %>"</img>
</p>

<p>
  <strong>Favorite:</strong>
  <%= @workout.favorite %>
</p>

<%= link_to 'Back', workouts_path %>
</div>